"""Global configuration commands."""

import os

import rich_click as click
from rich.console import Console
from rich.prompt import Confirm, Prompt

from mirustech.devenv_generator.settings import (
    ensure_config_dir,
    get_config_path,
    get_settings,
)

console = Console()


@click.group()
def config() -> None:
    """Manage devenv configuration."""
    pass


@config.command("show")
def show() -> None:
    """Display current configuration."""
    settings = get_settings()
    config_path = get_config_path()

    console.print("[bold]Registry Configuration:[/bold]")
    console.print(f"  Enabled: {settings.registry.enabled}")
    console.print(f"  URL: {settings.registry.url}")
    console.print(f"  Auth Method: {settings.registry.auth_method.value}")
    console.print(f"  Auto-push: {settings.registry.auto_push}")
    console.print(f"  Timeout: {settings.registry.timeout}s")

    if settings.registry.username:
        console.print(f"  Username: {settings.registry.username}")

    console.print()
    if config_path.exists():
        console.print(f"[dim]Config file: {config_path}[/dim]")
    else:
        console.print(f"[dim]Config file: {config_path} (not created yet)[/dim]")


@config.command("set-registry")
def set_registry() -> None:
    """Configure container registry settings interactively."""
    console.print()
    console.print("[bold]Registry Setup Wizard[/bold]")
    console.print("─" * 25)
    console.print()

    # Get registry URL
    registry_url = Prompt.ask(
        "Registry URL",
        default="git.mirus-tech.com",
    )

    # Get auth method
    console.print()
    console.print("[bold]Authentication method:[/bold]")
    console.print("  1. existing - Use existing docker login (recommended)")
    console.print("  2. stored   - Store credentials in config file")
    console.print("  3. prompt   - Prompt for credentials each time")
    auth_choice = Prompt.ask(
        "Choice",
        choices=["1", "2", "3", "existing", "stored", "prompt"],
        default="1",
    )

    auth_map = {"1": "existing", "2": "stored", "3": "prompt"}
    auth_method = auth_map.get(auth_choice, auth_choice)

    username = None
    password = None
    if auth_method == "stored":
        console.print()
        username = Prompt.ask("Username")
        password = Prompt.ask("Password/Token", password=True)

    # Auto-push setting
    console.print()
    auto_push = Confirm.ask("Auto-push after build?", default=False)

    # Write config file
    config_dir = ensure_config_dir()
    config_path = config_dir / "config.env"

    lines = [
        "# devenv-generator configuration",
        "# Generated by: devenv config set-registry",
        "",
        "DEVENV_REGISTRY__ENABLED=true",
        f"DEVENV_REGISTRY__URL={registry_url}",
        f"DEVENV_REGISTRY__AUTH_METHOD={auth_method}",
        f"DEVENV_REGISTRY__AUTO_PUSH={str(auto_push).lower()}",
    ]

    if username:
        lines.append(f"DEVENV_REGISTRY__USERNAME={username}")
    if password:
        lines.append(f"DEVENV_REGISTRY__PASSWORD={password}")
        console.print()
        console.print("[yellow]Warning: Password stored in plaintext.[/yellow]")
        console.print(
            "[dim]Consider encrypting with SOPS:[/dim]"
        )
        console.print(
            "[dim]  sops encrypt --in-place ~/.config/devenv-generator/config.env[/dim]"
        )

    config_path.write_text("\n".join(lines) + "\n")

    console.print()
    console.print(f"[green]✓ Configuration saved to {config_path}[/green]")


@config.command("edit")
def edit() -> None:
    """Open config file in editor."""
    config_dir = ensure_config_dir()
    config_path = config_dir / "config.env"

    # Create default config if doesn't exist
    if not config_path.exists():
        default_content = """# devenv-generator configuration
# See: devenv config set-registry

# Enable registry support
DEVENV_REGISTRY__ENABLED=false

# Registry URL
DEVENV_REGISTRY__URL=git.mirus-tech.com

# Authentication method: existing, stored, prompt
DEVENV_REGISTRY__AUTH_METHOD=existing

# Auto-push after build
DEVENV_REGISTRY__AUTO_PUSH=false
"""
        config_path.write_text(default_content)
        console.print(f"[dim]Created default config at {config_path}[/dim]")

    editor = os.environ.get("EDITOR", "vi")
    console.print(f"[dim]Opening {config_path} with {editor}...[/dim]")
    os.execvp(editor, [editor, str(config_path)])
